Fixed bug in filter-clues plugin
nexB/scancode-toolkit pull request #2353
Opened 2020-12-16 17:27 UTC by tushar912

Fixes #1758 

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

2020-12-22 10:37 UTC, AyanSinhaMahapatra commented on tests/scancode/test_cli.py
> +
A nitpick, keep only 2 blank lines between functions/classes.

2020-12-22 10:41 UTC, AyanSinhaMahapatra commented
@tushar912 Does `./scancode -clpieu --json-pp sample_filter_clues.json samples --filter-clues` run properly now? Could you post the output JSON here?

The 2 failing tests seem to be from other problems that are fixed in the release branch.

2020-12-22 11:14 UTC, AyanSinhaMahapatra commented
Also, could you change the commit message according to this doc - https://aboutcode.readthedocs.io/en/latest/contributing/writing_good_commit_messages.html

So, 
1. Add more context about what is changed in the commit body, 
2. change `fixes` to `fix` in both PR name and commit header. https://chris.beams.io/posts/git-commit/#imperative
etc.

2020-12-22 14:00 UTC, tushar912 commented
@AyanSinhaMahapatra I think it is working I am getting this json output
```json
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "3.2.3.post38.b14ca7b2a",
      "options": {
        "input": [
          "samples"
        ],
        "--copyright": true,
        "--filter-clues": true,
        "--json-pp": "sample_filter_clues.json",
        "--license": true,
        "--package": true
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2020-12-22T135503.132005",
      "end_timestamp": "2020-12-22T135643.575892",
      "duration": 100.44390892982483,
      "message": null,
      "errors": [],
      "extra_data": {
        "files_count": 33
      }
    }
  ],
  "files": [
    {
      "path": "samples",
      "type": "directory",
      "licenses": [],
      "license_expressions": [],
      "percentage_of_license_text": 0,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "packages": [],
      "scan_errors": []
    },
    {
      "path": "samples/README",
      "type": "file",
      "licenses": [],
      "license_expressions": [],
      "percentage_of_license_text": 0,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "packages": [],
      "scan_errors": []
    },
    {
      "path": "samples/screenshot.png",
      "type": "file",
      "licenses": [],
      "license_expressions": [],
      "percentage_of_license_text": 0,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "packages": [],
      "scan_errors": []
    },
    {
      "path": "samples/arch",
      "type": "directory",
      "licenses": [],
      "license_expressions": [],
      "percentage_of_license_text": 0,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "packages": [],
      "scan_errors": []
    },
    {
      "path": "samples/arch/zlib.tar.gz",
      "type": "file",
      "licenses": [],
      "license_expressions": [],
      "percentage_of_license_text": 0,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "packages": [],
      "scan_errors": []
    },
    {
      "path": "samples/JGroups",
      "type": "directory",
      "licenses": [],
      "license_expressions": [],
      "percentage_of_license_text": 0,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "packages": [],
      "scan_errors": []
    },
    {
      "path": "samples/JGroups/EULA",
      "type": "file",
      "licenses": [
        {
          "key": "jboss-eula",
          "score": 100.0,
          "name": "JBoss EULA",
          "short_name": "JBoss EULA",
          "category": "Proprietary Free",
          "is_exception": false,
          "owner": "JBoss Community",
          "homepage_url": null,
          "text_url": "http://repository.jboss.org/licenses/jbossorg-eula.txt",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:jboss-eula",
          "spdx_license_key": null,
          "spdx_url": "",
          "start_line": 3,
          "end_line": 108,
          "matched_rule": {
            "identifier": "jboss-eula.LICENSE",
            "license_expression": "jboss-eula",
            "licenses": [
              "jboss-eula"
            ],
            "is_license_text": true,
            "is_license_notice": false,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "2-aho",
            "rule_length": 1264,
            "matched_length": 1264,
            "match_coverage": 100.0,
            "rule_relevance": 100
          }
        }
      ],
      "license_expressions": [
        "jboss-eula"
      ],
      "percentage_of_license_text": 98.98,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "packages": [],
      "scan_errors": []
    },
    {
      "path": "samples/JGroups/LICENSE",
      "type": "file",
      "licenses": [
        {
          "key": "lgpl-2.1",
          "score": 100.0,
          "name": "GNU Lesser General Public License 2.1",
          "short_name": "LGPL 2.1",
          "category": "Copyleft Limited",
          "is_exception": false,
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/lgpl-2.1.html",
          "text_url": "http://www.gnu.org/licenses/lgpl-2.1.txt",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:lgpl-2.1",
          "spdx_license_key": "LGPL-2.1-only",
          "spdx_url": "https://spdx.org/licenses/LGPL-2.1-only",
          "start_line": 1,
          "end_line": 502,
          "matched_rule": {
            "identifier": "lgpl-2.1_101.RULE",
            "license_expression": "lgpl-2.1",
            "licenses": [
              "lgpl-2.1"
            ],
            "is_license_text": true,
            "is_license_notice": false,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "1-hash",
            "rule_length": 4281,
            "matched_length": 4281,
            "match_coverage": 100.0,
            "rule_relevance": 100
          }
        }
      ],
      "license_expressions": [
        "lgpl-2.1"
      ],
      "percentage_of_license_text": 100.0,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "packages": [],
      "scan_errors": []
    },
    {
      "path": "samples/JGroups/licenses",
      "type": "directory",
      "licenses": [],
      "license_expressions": [],
      "percentage_of_license_text": 0,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "packages": [],
      "scan_errors": []
    },
    {
      "path": "samples/JGroups/licenses/apache-1.1.txt",
      "type": "file",
      "licenses": [
        {
          "key": "apache-1.1",
          "score": 100.0,
          "name": "Apache License 1.1",
          "short_name": "Apache 1.1",
          "category": "Permissive",
          "is_exception": false,
          "owner": "Apache Software Foundation",
          "homepage_url": "http://www.apache.org/licenses/",
          "text_url": "http://apache.org/licenses/LICENSE-1.1",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:apache-1.1",
          "spdx_license_key": "Apache-1.1",
          "spdx_url": "https://spdx.org/licenses/Apache-1.1",
          "start_line": 2,
          "end_line": 56,
          "matched_rule": {
            "identifier": "apache-1.1_71.RULE",
            "license_expression": "apache-1.1",
            "licenses": [
              "apache-1.1"
            ],
            "is_license_text": true,
            "is_license_notice": false,
            "is_license_reference": false,
            "is_license_tag": false,
            "matcher": "1-hash",
            "rule_length": 361,
            "matched_length": 361,
            "match_coverage": 100.0,
            "rule_relevance": 100
          }
        }
      ],
      "license_expressions": [
        "apache-1.1"
      ],
      "percentage_of_license_text": 100.0,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "packages": [],
      "scan_errors": []
    },
    {
      "path": "samples/JGroups/licenses/apache-2.0.txt",
      "type": "file",
      "licenses": [
        {
          "key": "apache-2.0",
          "score": 100.0,
          "name": "Apache License 2.0",
          "short_name": "Apache 2.0",
          "category": "Permissive",
          "is_exception": false,
          "owner": "Apache Software Foundation",
          "homepage_url": "http://www.apache.org/licenses/",
        [...]

2021-01-14 08:05 UTC, pombredanne commented
@tushar912 @AyanSinhaMahapatra what's left to do here? I would like to merge this ASAP :)

2021-01-14 12:15 UTC, AyanSinhaMahapatra requested changes
@pombredanne I've tested this branch locally, the bug isn't there anymore, tests pass, and the plugin seems to be doing everything as it should, i.e. removing redundant duplicated clues already contained in detected license and copyright texts and notices. It seems ready to merge to me, but you should still check the changes to see everything is in place.

But the commit message has to be changed as it seems to have leftovers from squashing two commits together, having two bodies, and two signoffs. @tushar912

2021-01-14 12:47 UTC, tushar912 commented
@AyanSinhaMahapatra I have changed the commit message .I think it looks better now.

2021-01-14 12:53 UTC, AyanSinhaMahapatra commented
Another nitpick, adding the issue number on the commit header/body would be best. Just add `#1758` after bug in the header and that would be all. Sorry I missed this before. Thanks++

2021-01-14 13:00 UTC, tushar912 commented
@AyanSinhaMahapatra I have made the change.

2021-01-14 14:14 UTC, AyanSinhaMahapatra approved these changes

2021-01-29 10:33 UTC, pombredanne approved these changes
LGTM! Thank you++

2021-01-29 10:33 UTC, merged

2021-01-29 10:33 UTC, pombredanne commented
@AyanSinhaMahapatra please go ahead and merge

2021-01-29 10:34 UTC, pombredanne commented
@tushar912 Thank you ++ :bow: