Added new license Anti-Capitalist Software License #2362
nexB/scancode-toolkit pull request #2364
Opened 2021-01-12 13:39 UTC by itssingh

Signed-off-by: itssingh saritasingh.0425@gmail.com
Fixes #2362

 Added new licenses ANTI-CAPITALIST SOFTWARE LICENSE v-1.0, v-1.1, v-1.2, v-1.3 and v-1.4
### These added licenses are giving correct scan result. 

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

2021-02-26 21:23 UTC, pombredanne requested changes
Thanks! I have a few nitpickings for your consideration before we can merge.

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.0.LICENSE
> +Copyright © [year] [copyright holders]
Please do not include a "dummy" copyright template in the license text 
```suggestion
```

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.0.yml
> +    - https://anticapitalist.software/past_versions/
Can you add a trailing line return?

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.1.LICENSE
> +Copyright © [year] [copyright holders]
Same above: no copyright template there
```suggestion
```

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.2.LICENSE
> +Copyright © [year] [copyright holders]
Same as above.
```suggestion
```

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.3.LICENSE
> +Copyright © [year] [copyright holders]
```suggestion
```

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.4.LICENSE
> +Copyright © [year] [copyright holders]
```suggestion
```

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.3.yml
> +    - https://anticapitalist.software/past_versions/
Add trailing LF

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.3.LICENSE
> +THE SOFTWARE IS PROVIDED "AS IS", WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
Add trailing LF

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.2.yml
> +    - https://anticapitalist.software/past_versions/
Add trailing LF

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.2.LICENSE
> +THE SOFTWARE IS PROVIDED "AS IS", WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
Add trailing LF

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.1.yml
> +    - https://anticapitalist.software/past_versions/
Add trailing LF

2021-02-26 21:23 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.1.LICENSE
> +THE SOFTWARE IS PROVIDED "AS IS", WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
Add trailing LF

2021-03-29 12:03 UTC, pombredanne requested changes
@itssingh  Thank you! Almost there too here!

See the "ignorables"-related test failures in https://dev.azure.com/nexB/scancode-toolkit/_build/results?buildId=3262&view=logs&j=3c16b29b-eb82-5c7a-26ca-153f5e2ef8d4&t=525ae439-c19a-5d45-abf1-df81b3df2f93&l=43551 for your review.

2021-03-30 04:05 UTC, itssingh commented
> See the "ignorables"-related test failures

There is no need of putting ignorable_url in rule as I concluded from scan result and since test is also falling on that I should better remove them, right?

```
"licenses": [
        {
          "key": "anti-capitalist-1.4",
          "score": 100.0,
          "name": "ANTI-CAPITALIST SOFTWARE LICENSE (v 1.4)",
          "short_name": "ACSL v. 1.4",
          "category": "Free Restricted",
          "is_exception": false,
          "owner": "Everest Pipkin and Ramsey Nasser",
          "homepage_url": "https://anticapitalist.software/",
          "text_url": "",
          "reference_url": "https://scancode-licensedb.aboutcode.org/anti-capitalist-1.4",
          "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/anti-capitalist-1.4.LICENSE",
          "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/anti-capitalist-1.4.yml",
          "spdx_license_key": null,
          "spdx_url": "",
          "start_line": 1,
          "end_line": 12,
          "matched_rule": {
            "identifier": "anti_capitalist2.RULE",
            "license_expression": "anti-capitalist-1.4",
            "licenses": [
              "anti-capitalist-1.4"
            ],
            "is_license_text": true,
            "is_license_notice": false,
            "is_license_reference": false,
            "is_license_tag": false,
            "is_license_intro": false,
            "matcher": "1-hash",
            "rule_length": 245,
            "matched_length": 245,
            "match_coverage": 100.0,
            "rule_relevance": 100
          }
        }
      ],
```

@pombredanne relevance=100 is okay?

2021-06-02 07:59 UTC, pombredanne reviewed
> should I put url in notes: 

no, you just need to add `ignorable_*` fields for URLs and emails

2021-06-02 07:59 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.4.yml
> +ignorable_urls:
```suggestion
```

2021-06-02 07:59 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.4.yml
> +    - https://anticapitalist.software/past_versions/
```suggestion
```

2021-06-02 07:59 UTC, pombredanne commented on src/licensedcode/data/rules/anti_capitalist1.yml
> +    - https://anticapitalist.software/past_versions/
```suggestion
```

2021-06-02 07:59 UTC, pombredanne commented on src/licensedcode/data/rules/anti_capitalist1.yml
> +ignorable_urls:
```suggestion
```

2021-06-03 14:59 UTC, pombredanne requested changes
Thank you! Please consider the few cleanups I suggested. Also feel free to squash all your commits in a single one.

2021-06-03 14:59 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.4.yml
> +
```suggestion
spdx_license_key: LicenseRef-scancode-anti-capitalist-1.4
```

2021-06-03 14:59 UTC, pombredanne commented on src/licensedcode/data/licenses/anti-capitalist-1.4.yml
> +
```suggestion
```

2021-06-03 14:59 UTC, pombredanne commented on src/licensedcode/data/rules/anti_capitalist1.yml
> +
```suggestion
```

2021-06-03 14:59 UTC, pombredanne commented on src/licensedcode/data/rules/anti_capitalist2.yml
> +
```suggestion
```

2021-06-03 14:59 UTC, pombredanne commented on src/licensedcode/data/rules/anti_capitalist3.yml
> +
```suggestion
```

2021-06-03 14:59 UTC, pombredanne commented on src/licensedcode/data/rules/anti_capitalist4.yml
> +
```suggestion
```

2021-06-04 00:33 UTC, itssingh commented
> consider the few cleanups I suggested

I left these https://github.com/nexB/scancode-toolkit/pull/2364#discussion_r644868769 as trailing line return        https://github.com/nexB/scancode-toolkit/pull/2364#discussion_r583924347 as you previously suggested. Removed now :)

2021-08-10 09:51 UTC, itssingh commented
@pombredanne Should I add notes for all the rules?

2021-08-25 08:49 UTC, pombredanne commented
FYI I merged the latest develop and fixed the tests, then pushed back to your branch

2021-08-25 11:59 UTC, pombredanne approved these changes
LGTM. Merging now at last. Thanks!

2021-08-25 11:59 UTC, merged