Filter Ignorable Copyrights #372
nexB/scancode-toolkit pull request #2436
Opened 2021-03-12 13:41 UTC by adityaviki

Signed-off-by: adityaviki <adityaviki01@gmail.com>

2021-03-21 06:36 UTC, adityaviki commented
@pombredanne let me know if I need to make any improvements to the code. I'll write the the tests for it afterwards.

2021-03-21 08:46 UTC, itssingh commented
Can you edit the top comment and linked issue no!

2021-03-24 17:57 UTC, pombredanne requested changes
Thank you ++
This is looking great! :bow: 
It is missing one thing though before I can merge: some test.
Do you think you can draft one?

2021-03-24 17:57 UTC, pombredanne commented on docs/source/cli-reference/help-text-options.rst
> +      --filter-ignoralbe-copyrights   Filter out copyrights that are for the
I think we have a tiny typo:
`--filter-ignoralbe-copyrights` should be `--filter-ignorable-copyrights`
```suggestion
      --filter-ignorable-copyrights   Filter out copyrights that are for the 
```

2021-03-30 07:10 UTC, adityaviki commented
> Do you think you can draft one?
Yes of course :)

2021-03-30 08:11 UTC, adityaviki commented
> Can you please edit the top comment and linked issue no along with your name!

Sorry! I didn't understand. Do I need to add

2021-03-30 08:16 UTC, adityaviki commented
I didn't meant to close the PR or delete the branch. I wasn't  paying  attention to where I was clicking. :/

2021-03-30 12:44 UTC, pombredanne requested changes

2021-03-30 12:44 UTC, pombredanne commented on src/cluecode/plugin_filter_ignorable_copyrights.py
> +from commoncode.cliutils import OUTPUT_FILTER_GROUP
Could add a header comment matching other files?

2021-03-30 15:55 UTC, pombredanne commented
> I didn't mean to close the PR or delete the branch. I wasn't paying attention to where I was clicking. :/

that's OK :)

2021-03-30 15:56 UTC, pombredanne commented on src/cluecode/plugin_filter_ignorable_copyrights.py
> +from commoncode.cliutils import OUTPUT_FILTER_GROUP
```suggestion
#
# Copyright (c) nexB Inc. and others. All rights reserved.
# ScanCode is a trademark of nexB Inc.
# SPDX-License-Identifier: Apache-2.0
# See http://www.apache.org/licenses/LICENSE-2.0 for the license text.
# See https://github.com/nexB/scancode-toolkit for support or download.
# See https://aboutcode.org for more information about nexB OSS projects.
#

from commoncode.cliutils import OUTPUT_FILTER_GROUP
```

2021-03-30 15:58 UTC, pombredanne approved these changes

2021-04-02 05:24 UTC, adityaviki commented
@pombredanne I don't know how to solve the failing check.

2021-04-18 03:31 UTC, itssingh commented
>I don't know how to solve the failing check.

DCO check is falling because of this https://github.com/nexB/scancode-toolkit/pull/2436/commits/55cea2679297d4f7cd757c8a922b1c0f32906c47 It has co-authour name but signed-off is missing. So what you can do is squash these changes to the original commit of your and add sign-off or you may ask @pombredanne to squash all the commits into one.

2021-08-03 06:16 UTC, adityaviki commented
@itssingh It's still not clear how to solve the issue.

2023-01-17 08:09 UTC, pombredanne commented
@adityaviki this will be merged at last in v32.1 ... but it may be partially redundant with pre-existing ScanCode CLI options

2023-11-13 13:02 UTC, pombredanne commented
https://github.com/nexB/scancode-toolkit/blob/develop/src/cluecode/plugin_filter_clues.py has the feature and predates this PR. Thank you +++, closing.

2023-11-13 13:02 UTC, closed without merging