Factor out a detect_copyrights_from_lines() function that doesn't rely on textcode
nexB/scancode-toolkit pull request #2476
Opened 2021-04-02 12:43 UTC by jelmer

Factor out a detect_copyrights_from_lines() function that doesn't rely on textcode.

2021-04-11 15:30 UTC, pombredanne requested changes
LGTM!
Thanks. Do you mind to add a DCO signoff?
Either in your commit or in the may text of the PR.
We could also add a simple test?

2021-04-13 16:27 UTC, jelmer commented
I've added Signed-Off-By - I can have a look at adding a test later this week.

2021-04-13 17:31 UTC, pombredanne commented
Thanks! I can merge as is alright too.

2021-05-21 13:57 UTC, merged

2021-05-21 13:57 UTC, pombredanne commented
@jelmer Thanks!