Introduce output data format versioning #2653 [WIP]
nexB/scancode-toolkit pull request #2682
Opened 2021-08-30 14:15 UTC by AyanSinhaMahapatra

Add output data format version numbers to the headers and version help
text. Introduce new command line option to switch to the new experimental
data format.

Signed-off-by: Ayan Sinha Mahapatra <ayansmahapatra@gmail.com>

2021-09-03 12:16 UTC, AyanSinhaMahapatra commented
@pombredanne could you look into this why the tests with `latest_from_pip` are failing like [here](https://dev.azure.com/nexB/scancode-toolkit/_build/results?buildId=4557&view=logs&j=9a634e43-2dfe-534b-56d2-0b7ffad252eb&t=28d573b5-74f3-578a-960b-e035b88f9a42). These are failing as `bin/pip install --force-reinstall --upgrade -e .[dev]` replaces commoncode `21.8.31` with `21.8.27`, which doesn't have the header changes, and hence the failures. 

If I change [this](https://github.com/nexB/scancode-toolkit/blob/develop/setup.cfg#L62) to `21.8.31`, this happens in the test:

```
ERROR: Could not find a version that satisfies the requirement commoncode>=21.8.31 (from scancode-toolkit[dev]) (from versions: 20.9, 20.9.30, 20.10, 20.10.8, 20.10.20, 21.1.14, 21.1.21, 21.4.28, 21.5.12, 21.5.25, 21.6.10, 21.6.11, 21.7.23, 21.8.27)
ERROR: No matching distribution found for commoncode>=21.8.31
```
What am I doing wrong here

2021-09-06 10:04 UTC, pombredanne commented on src/scancode/cli.py
> +    help='Output the next experimental data format, for JSON and YAML output.'
Use future and not experimental, here and elsewhere

2021-09-06 10:05 UTC, pombredanne commented on src/scancode_config.py
> +__output_format_version__ = '1.1'
let's use 1.0

2021-09-06 10:18 UTC, pombredanne commented
> 21.8.31

You need to push 21.8.31 to PyPI too IMHO

2021-09-06 10:30 UTC, pombredanne requested changes
IMHO you could have fewer changes in the diffs if `def check_json_scan(..., ignore_headers=True)` was updated to be  `def check_json_scan(..., include_headers=False)` this way few changes are needed in the tests overall... and only a few tests that test headers will need fixing.

2021-09-06 12:03 UTC, AyanSinhaMahapatra commented
> You need to push 21.8.31 to PyPI too IMHO

You have to add me at https://pypi.org/project/commoncode/ btw

2021-09-14 20:06 UTC, pombredanne approved these changes
LGTM. Merging!

2021-09-14 20:07 UTC, merged