Replace freenode references with libera chat
nexB/scancode-toolkit pull request #2816
Opened 2022-01-26 11:12 UTC by PurnaChandraMansingh

Signed-off-by: Purna Chandra Mansingh <purnachandramansingh135@gmail.com>

Fixes [#92](https://github.com/nexB/aboutcode/issues/92)

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

2022-01-27 15:41 UTC, pombredanne commented
You wrote:

> Fixes #92

I would doubt that you meant https://github.com/nexB/scancode-toolkit/issues/92 ?
Could you instead use the full URL to the main issue in AboutCode?

2022-01-27 15:43 UTC, pombredanne requested changes
Thanks ... See my comments inline

2022-01-27 15:43 UTC, pombredanne commented on tests/licensedcode/data/datadriven/external/fossology-tests/Apache/etcd.txt
> -- IRC: #[etcd](irc://irc.freenode.org:6667/#etcd) on freenode.org
This is a test file... not a doc file for our code... do not modifiy this

2022-01-27 15:43 UTC, pombredanne commented on tests/packagedcode/data/pypi/setup.py-versions/cffi-1.14.0/setup.py
> +    the IRC channel https://gitter.im/aboutcode-org/discuss)
This is a test file... not a doc file for our code... do not modifiy this

2022-01-27 15:43 UTC, pombredanne commented on tests/packagedcode/data/pypi/unpacked_wheel/metadata-2.1/pip-20.2.2.dist-info-expected.json
> +    "description": "The PyPA recommended tool for installing Python packages.\npip - The Python Package Installer\n==================================\n\n.. image:: https://img.shields.io/pypi/v/pip.s
This is a test file... not a doc file for our code... do not modifiy this

2022-01-27 15:43 UTC, pombredanne commented on tests/packagedcode/data/pypi/unpacked_wheel/metadata-2.1/pip-20.2.2.dist-info/METADATA
> +.. _Development IRC: https://web.libera.chat/?#aboutcode
This is a test file... not a doc file for our code... do not modifiy this

2022-01-27 15:50 UTC, PurnaChandraMansingh commented
Thank you so much @pombredanne, I thought I have to change every Freenode reference but I have to change the Freenode references which are only present in the documentation. 
I will do the necessary changes and will push it again.

2022-01-29 22:01 UTC, pombredanne approved these changes
Looking great. Thanks

2022-01-29 22:01 UTC, merged