Add Note for Windows User in NewComer
nexB/scancode-toolkit pull request #2847
Opened 2022-02-03 17:01 UTC by OsmiumOP

Signed-off-by: Harsh Bansal <harshbansal.contact@gmail.com>

Fixes #2845 
Simple addition to documentation I feel should be a good thing for any New Comer like me 😄 

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

2022-02-05 11:04 UTC, OsmiumOP commented
@pombredanne can you check this?

2022-02-07 14:20 UTC, pombredanne requested changes
hey, there may be some mixup? There is entirely unrelated code in this PR.

2022-02-07 14:20 UTC, pombredanne commented on src/cluecode/copyrights.py
> +    # Copyright lowRISC contributors.
How is this related to this PR?

2022-02-07 14:23 UTC, OsmiumOP commented on src/cluecode/copyrights.py
> +    # Copyright lowRISC contributors.
Should I re-fork and do the changes again?

2022-02-07 14:29 UTC, closed without merging

2022-02-07 14:36 UTC, pombredanne commented on src/cluecode/copyrights.py
> +    # Copyright lowRISC contributors.
Your call.... this can work. Also learning git merge/rebase/amend is a very useful skill to nurture.

2022-02-07 14:44 UTC, OsmiumOP commented on src/cluecode/copyrights.py
> +    # Copyright lowRISC contributors.
Ok sir, I re-forked and reopened the PR. 
Will surely look into merge/rebase/amend as soon as I get time from exams.