Modify pypi PKG-INFO parse
nexB/scancode-toolkit pull request #2953
Opened 2022-05-11 15:59 UTC by AyanSinhaMahapatra

Reference: #2943
Do not return 2 PackageData objects when there are PKG-INFO files.

Signed-off-by: Ayan Sinha Mahapatra <ayansmahapatra@gmail.com>

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

2022-05-11 17:01 UTC, JonoYang commented
@AyanSinhaMahapatra LGTM!

2022-05-12 17:07 UTC, pombredanne requested changes
Thanks. See my nits!

2022-05-12 17:07 UTC, pombredanne commented on src/packagedcode/pypi.py
> +        if not PythonEggPkgInfoFile.is_datafile(location) and not\
Please avoid back-slashes for line continuations. Prefer instead using `()` parens.
```suggestion
        if (not PythonEggPkgInfoFile.is_datafile(location) and not
```

2022-05-12 17:07 UTC, pombredanne commented on src/packagedcode/pypi.py
> +        if not PythonEggPkgInfoFile.is_datafile(location) and not\
Also I think it would be best overriding is_datafile() for this

2022-05-12 18:41 UTC, AyanSinhaMahapatra commented on src/packagedcode/pypi.py
> +        if not PythonEggPkgInfoFile.is_datafile(location) and not\
Made the requested changes.

2022-05-13 21:14 UTC, pombredanne reviewed
Great!

2022-05-13 21:14 UTC, pombredanne approved these changes

2022-05-13 21:14 UTC, merged