(docs) update `--shallow` description
nexB/scancode-toolkit pull request #2959
Opened 2022-05-17 12:20 UTC by lf32

Fixes #2895

2022-05-17 16:52 UTC, AyanSinhaMahapatra requested changes

2022-05-17 16:52 UTC, AyanSinhaMahapatra commented on docs/source/tutorials/how_to_run_a_scan.rst
> +    ``--shallow`` option can be used to prevent recursive extraction of nested archives.
```suggestion
    Use the ``--shallow`` option to prevent recursive extraction of nested archives. 
```

2022-05-18 05:51 UTC, lf32 commented on docs/source/tutorials/how_to_run_a_scan.rst
> +    ``--shallow`` option can be used to prevent recursive extraction of nested archives.
Done!

2022-05-20 14:10 UTC, pombredanne commented
Thanks! I am going to merge this, but the all purpose of the DCO signoff is to show a real name with a real email address, and not just to pass the DCO bot check.... here `Signed-off-by: lf32 <96695352+lf32@users.noreply.github.com>` is nothing like this, so I will really need you to fix this in any future submissions! ;)

2022-05-20 20:54 UTC, pombredanne approved these changes
LGTM. Merging now. Thanks!

2022-05-20 20:55 UTC, merged

2022-05-21 13:40 UTC, lf32 commented
Thanks! Yes I'll get this fixed.