Prefer using PKG-INFO from .egg-info in assemble #3083
nexB/scancode-toolkit pull request #3091
Opened 2022-09-03 00:57 UTC by JonoYang

This PR addresses #3083, where we have no dependencies returned when we scanned an installable Python codebase. This issue is cause by `BaseExtractedPythonLayout.assemble()`, where it would use the package data from the PKG-INFO file from the root of a Python codebase rather than from the PKG-INFO file from the .egg-info directory (also located in the root of a Python codebase). 

We want to use the PKG-INFO file from the .egg-info directory because the package data from that contains the dependency information.

2022-09-03 13:16 UTC, pombredanne requested changes
Thanks!
There are a few nit that likely are leftover from before... we should better track the extracted requirements and treat PyPI extras as optional

2022-09-03 13:16 UTC, pombredanne commented on tests/packagedcode/data/pypi/unpacked_sdist/prefer-egg-info-pkg-info/celery-expected.json
> +              "scope": "azurebl
We should have an extracted requirement of "msgpack"

2022-09-03 13:16 UTC, pombredanne commented on tests/packagedcode/data/pypi/unpacked_sdist/prefer-egg-info-pkg-info/celery-expected.json
> +              "scope": "azurebl
We should have instead:
```suggestion
              "extracted_requirement": "couchbase>=3.0.0",
```

2022-09-03 13:16 UTC, pombredanne commented on tests/packagedcode/data/pypi/unpacked_sdist/prefer-egg-info-pkg-info/celery-expected.json
> +      "is_optional": false,
IMHO we should be true for "extras" e.g. not an "install_requires" and therefore not in "install" scope:
```suggestion
      "is_optional": true,
```

2022-09-06 21:55 UTC, JonoYang commented
I've updated the code to return the dependency name in the extracted_requirements and to properly set the is_optional field on the dependencies listed in extra_requires.

Tests are passing, so I will merge this.

2022-09-06 21:55 UTC, merged