Add package_releases in packagedata model
nexB/scancode-toolkit pull request #3111
Opened 2022-09-19 18:32 UTC by TG1999

Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>

Add package_releases in packagedata model to have more than one downloadable url per package

Fixes #0000

### Tasks

* [ ] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [ ] Commits are in uniquely-named feature branch and has no merge conflicts 📁

2022-09-19 18:36 UTC, TG1999 commented
@AyanSinhaMahapatra @pombredanne @JonoYang please have a look on these model changes, please give your suggestion on this and do let me know if these model changes are useful in anyway.

2022-09-19 19:41 UTC, JonoYang requested changes
@TG1999 

Where will the package_releases field be used? Is it something that scancode toolkit will populate or is it going to be used by another library?

Also, your regenerated test files have issues with some of the expected license_expressions. License expressions that were detected properly as gpl-2.0, gpl-3.0, lgpl-2.1, etc. are now being reported as `unknown`.

2022-09-19 19:41 UTC, JonoYang commented on src/packagedcode/models.py
> +    wheel,
It feels strange to have package-specific release types in the base models.py file.

2022-09-19 19:41 UTC, JonoYang commented on tests/packagedcode/data/alpine/alpine-container-layer.tar.xz-get-installed-expected.json
> +    "license_expression": "unknown",
The expected license expression should not be changed.

You may need to run `scancode --reindex-licenses` before regenerating the test results.

2023-01-06 11:05 UTC, pombredanne commented
@TG1999 IMHO we should close this and instead have an issue to revisit the topic of packages vs. download URLs.

2023-01-06 11:24 UTC, closed without merging

2023-01-06 12:00 UTC, TG1999 commented
Added issue https://github.com/nexB/scancode-toolkit/issues/3188