fix(nuget): add nuget dependency extract
nexB/scancode-toolkit pull request #3121
Opened 2022-10-06 06:57 UTC by hellhound-abu

Fixes #0000

### Tasks

* [ ] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [ ] Commits are in uniquely-named feature branch and has no merge conflicts 📁

2022-10-10 09:43 UTC, AyanSinhaMahapatra commented
Thanks! Could you fix the test failures at `tests/packagedcode/test_nuget.py` with:

* `pytest -vvs tests/packagedcode/test_nuget.py` and then
* `SCANCODE_REGEN_TEST_FIXTURES=yes pytest -vvs tests/packagedcode/test_nuget.py --lf`

Also please add your signoff. :bow:

2022-10-28 15:37 UTC, pombredanne commented
@hellhound-abu gentle ping.. we would like to merge this... but we cannot unless you update your PR at least with a DCO signoff.

2022-10-28 15:41 UTC, pombredanne commented
@6mile ping you seem to be from the same group, may be you can help there?

2022-10-28 20:46 UTC, 6mile commented
> @6mile ping you seem to be from the same group, may be you can help there?

I've let him know.  Cheers.

2022-10-29 00:57 UTC, jaitaiwan commented
Hey folks, Dan from SecureStack here. Abu is on holidays so won’t be able to contribute till 2 weeks from now. I can fix the failing tests if that’s helpful but that won’t help get a DCO from him.

Do you have a way around this or content to wait?

2022-10-29 08:55 UTC, pombredanne commented
@jaitaiwan Thank you ++ for your reply! 
No rush,  we can wait alright!
We are just making sure we do not have too many PRs that could go stale from lack of TLC especially like this one which is valuable addition.
 
Whatever you guys are doing on SecureStack looks great BTW! :+1:

2022-11-14 16:58 UTC, pombredanne commented
@hellhound-abu gentle ping ... you may be back now?

2022-11-22 03:51 UTC, hellhound-abu commented
Updated the branch with necessary changes. If we can merge it whenever possible.

Thanks for waiting.

2022-11-22 10:29 UTC, pombredanne requested changes
@hellhound-abu Thank you ++ for the updates! I posted a few review comments inline for your consideration. There is also one failing test.

2022-11-22 10:29 UTC, pombredanne commented on src/packagedcode/nuget.py
> +# TODO: Add section to handle dependencies of dependencies
For this you may want to create a separate issue... TODO comments (that I tend to abuse) eventually get lost.
Note also that for a full, dynamic dependency resolution of nugets. there is this new project at https://github.com/nexB/nuget-inspector

2022-11-22 10:29 UTC, pombredanne commented on src/packagedcode/nuget.py
> +                            version=dependency.get("@version"),
You can only put a version here if this is not a range so IMHO you would have to test for this.

2022-11-22 10:29 UTC, pombredanne commented on src/packagedcode/nuget.py
> +                            scope="dependency",
Would not each dependency group become a scope here?

2022-11-22 10:29 UTC, pombredanne commented on src/packagedcode/nuget.py
> +                            is_resolved=True,
A dependency is resolved if an only if we have a concrete version and not a range. Here the version is optional AFAIK and could be a range?

2022-11-22 10:29 UTC, pombredanne commented on src/packagedcode/nuget.py
> +            if "dependency" in nuspec.get("dependencies"):
I would prefer something like this, and then reuse the `nuget_dependency` var below:
```suggestion
            nuget_dependencies = nuspec.get("dependencies") or {}
            nuget_dependency = nuget_dependencies.get("dependency")
            if nuget_dependency:
```

2022-11-22 10:29 UTC, pombredanne commented on src/packagedcode/nuget.py
> +                            "dependency").get("@version"),
Factor version here and above in a variable.

2022-11-22 10:29 UTC, pombredanne commented on src/packagedcode/nuget.py
> +                        is_resolved=True,
Same comment as above... resolve is True IFF we have a concrete pinned, non-empty version

2022-11-22 10:29 UTC, pombredanne commented on src/packagedcode/nuget.py
> +        print(e)
Please do not print exceptions. In general your should avoid to wrap you code in a try/except altogether as this can never be debugged this way. Let the exception bubble up and we will catch it where needed, and worse case at the top level.

2022-11-22 10:29 UTC, pombredanne commented on src/packagedcode/nuget.py
> +        description = build_description(
Why wrapping this on tow lines? I am not sure this helps with readability.

2022-11-22 10:29 UTC, pombredanne commented on tests/packagedcode/data/nuget/bootstrap.nuspec.json.expected
> +          "type": "nuget",
Please avoid changing the spacing if possible as this makes reviewing the diff difficult

2022-11-22 10:34 UTC, jaitaiwan commented on src/packagedcode/nuget.py
> +# TODO: Add section to handle dependencies of dependencies
I say the same thing about TODO's internally 😂 That nuget-inspector proejct looks promising.

2022-11-22 10:36 UTC, jaitaiwan commented on src/packagedcode/nuget.py
> +            if "dependency" in nuspec.get("dependencies"):
Out of curiosity, any reason for `or {}` over `get("...", {})`?

2022-11-22 10:44 UTC, pombredanne commented on src/packagedcode/nuget.py
> +            if "dependency" in nuspec.get("dependencies"):
@jaitaiwan re:

> Out of curiosity, any reason for or {} over get("...", {})?

This is an idiom I like to use to make sure that I am getting a proper empty dict in all cases even if the get returns None or some emptyish value.
Getting an empty dict when you expect a dict enable chaining the next call without requiring an extra check for empties.

```Python
>>> repr({1: None, 2: "", 3: {"bar": "baz"}}.get(1, {}))
'None'
>>> repr({1: None, 2: "", 3: {"bar": "baz"}}.get(1, {}) or {})
'{}'
>>> repr({1: None, 2: "", 3: {"bar": "baz"}}.get(1) or {})
'{}'

```

2022-11-22 10:46 UTC, jaitaiwan commented on src/packagedcode/nuget.py
> +            if "dependency" in nuspec.get("dependencies"):
Fair call. thanks!

2023-01-04 09:58 UTC, pombredanne commented
@hellhound-abu Happy new year! gentle ping

2023-01-09 15:46 UTC, pombredanne commented
@AyanSinhaMahapatra since there is no reply for now, let's move this to the next milestone

2023-01-09 15:48 UTC, AyanSinhaMahapatra commented
@pombredanne moved this to v32.1

2023-01-18 00:14 UTC, pombredanne commented
I have applied the fixes in https://github.com/nexB/scancode-toolkit/pull/3206 on top of you commits. So I am losing this and will merge this other branch!
Thanks!

2023-01-18 00:14 UTC, closed without merging