Fix licenses in HTML output
nexB/scancode-toolkit pull request #3275
Opened 2023-02-24 06:52 UTC by AyanSinhaMahapatra

Fixes #3272 

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

2023-02-24 12:46 UTC, pombredanne requested changes
LGTM, but we need a test

2023-02-28 12:12 UTC, jbohrmann commented
Hi, license text is not included in HTML-output. As I am new to scancode I am not sure if this is expected behavior.
I run scancode under windows (py 3.9).
I call it this way (--license-text-diagnostics also does not change the output):
`scancode.bat -cleui -n 2 --html output.html . --license-score 2 --license-text --license-text-diagnostics`

2023-02-28 12:36 UTC, AyanSinhaMahapatra commented
@jbohrmann can you confirm that you used the checkout of this branch?

```
git clone https://github.com/nexB/scancode-toolkit.git
git checkout fix-html-output
./configure --dev
 scancode -clipeu --html output.html samples/
```

I seem to have licenses fine from this branch, attaching here the output.html file I generated using these commands above:
[output.html](https://github.com/nexB/scancode-toolkit/files/10850279/output.html.txt)

Also `--html` is a very basic output format, and does not have support for most of the advanced CLI options such as the one you have used:
* --license-score
*  --license-text 
* --license-text-diagnostics
Use --json or --yaml to use all the supported CLI options.

2023-02-28 13:00 UTC, jbohrmann commented
> @jbohrmann can you confirm that you used the checkout of this branch?
> 
> ```
> git clone https://github.com/nexB/scancode-toolkit.git
> git checkout fix-html-output
> ./configure --dev
>  scancode -clipeu --html output.html samples/
> ```
> 
> I seem to have licenses fine from this branch, attaching here the output.html file I generated using these commands above: [output.html](https://github.com/nexB/scancode-toolkit/files/10850279/output.html.txt)
> 
> Also `--html` is a very basic output format, and does not have support for most of the advanced CLI options such as the one you have used:
> 
> * --license-score
> * --license-text
> * --license-text-diagnostics
>   Use --json or --yaml to use all the supported CLI options.

Yes I can confirm.
Here is the info from my .VERSION file:

`refs=refs/pull/3275/head, fix-html-output`

I preferred HTML as I can pass the output easily to get legal advice.

2023-02-28 13:45 UTC, AyanSinhaMahapatra commented
@jbohrmann what is your OS? also what is your installation process? Is it a git checkout or an app archive download? the .VERSION file looks like this https://github.com/nexB/scancode-toolkit/blob/develop/.VERSION when you are installing from a git checkout, what do you mean info from this file?
Can you do a `git describe --tag` for me and confirm that the output is `v32.0.0rc2-2-g76795acd45` which is the last commit here? 

See above the commit with added test for licenses in html, looks like they work fine now after these changes ^

2023-03-01 15:32 UTC, pombredanne commented
@AyanSinhaMahapatra @jbohrmann said it was Windows and Python 3.9 ;)
>  I run scancode under windows (py 3.9).

2023-03-01 15:33 UTC, pombredanne commented
but afaics, we do not include the license text be it the matched text or the reference text in the standard HTML output. Maybe we should. HTML is nicer than JSON for sure.

2023-03-01 15:45 UTC, AyanSinhaMahapatra commented
@pombredanne We could have support for license-text, summary, license-clarity-score and others too in the HTML output, I opened an issue for this: https://github.com/nexB/scancode-toolkit/issues/3281.

2023-03-02 07:39 UTC, jbohrmann commented
I downloaded the branch as zip over Github. OS is Windows 10. 
Maybe it would be helpful to mention in the documentation that at the moment _--html_ does not support all features.

2023-03-02 09:33 UTC, pombredanne commented
>  Maybe it would be helpful to mention in the documentation that at the moment --html does not support all features.

@jbohrmann you are right! Note that there are a few alternatives:
- scancode.io provides a web ui to display the matched license text
- it is possible otherwise to create a custom HTML template that would include the matched text

2023-03-28 10:42 UTC, pombredanne commented on src/formattedcode/templates/html/template.html
> -            <td>{{ license.homepage_url|urlize(target='_blank') }}</td>
May be we should keep the homepage_url

2023-03-28 15:32 UTC, AyanSinhaMahapatra commented on src/formattedcode/templates/html/template.html
> -            <td>{{ license.homepage_url|urlize(target='_blank') }}</td>
Added this.

2023-03-31 21:12 UTC, JonoYang approved these changes
LGTM. I've tested out the HTML output on a scan of the samples directory and the results look great. Thanks!

2023-04-03 08:12 UTC, AyanSinhaMahapatra commented
Thanks @JonoYang , merging!

2023-04-03 08:12 UTC, merged