bug: add double curly braces
nexB/scancode-toolkit pull request #3644
Opened 2024-01-18 06:49 UTC by dotarjun

Fixes #3615

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁
* [x] Updated documentation pages (if applicable)
* [x] Updated CHANGELOG.rst (if applicable)

2024-01-18 12:30 UTC, AyanSinhaMahapatra requested changes
thanks @dotarjun 
We have to make sure here the detection issue is fixed completely.
When you're fixing these issues do attach scan results here:
[custom-content.html.txt.json](https://github.com/nexB/scancode-toolkit/files/13976481/custom-content.html.txt.json)
`scancode -l --license-text --license-diagnostics --license-text-diagnostics --license-references --todo custom-content.html.txt  --json-pp custom-content.html.txt.json`

1. Here we still have a `cc-by-sa-4.0` detection which is  incorrect, matched to https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/cc-by-sa-4.0_44.RULE so we have to add a required phrase there too.
This is a process of adding a change (be it a new rule or adding a required phrase to an old rule), reindex with `scancode-reindex-licenses` and scan again to check that the detection issue is fixed and the results are correct.
2. We can also improve the commit message and content. `bug: add double curly braces ` -> `Add required phrases to rules` and add the lines:  
```
Reference: https://github.com/nexB/scancode-toolkit/issues/3615
Reported-by: @camillem 
``` 
See also https://aboutcode.readthedocs.io/en/fix-rtd-pages/contributing/writing_good_commit_messages.html

2024-01-19 07:45 UTC, dotarjun commented
By following that command, I was running into this error: 

```
❯ scancode -l --license-text --license-diagnostics --license-text-diagnostics --license-references --todo custom-content.html.txt  --json-pp custom-content.html.txt.json
Usage: scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...
Try the 'scancode --help' option for help on options and arguments.

Error: Invalid value for '<OUTPUT FORMAT OPTION(s)> <input>...': Path 'custom-content.html.txt' does not exist.
```
![image](https://github.com/nexB/scancode-toolkit/assets/71163609/8a73110c-49a8-4f98-850f-2dc0d1b45b98)

So I ran this instead. This command did make some changes to ``custom-content.html.txt.json``
```
scancode -l --license-text --license-diagnostics --license-text-diagnostics --license-references --todo custom-content.html.txt.json --json-pp custom-content.html.txt.json
```
But then I am unable to figure out what is going on. 

For reference, I am using arch linux and my dev env is setup as per https://scancode-toolkit.readthedocs.io/en/latest/getting-started/install.html#installation-from-source-code-git-clone. I have it configured with ``--dev`` as well. 

Concerning the git commit message,
I have read the page that you linked and will update it.

2024-02-08 15:18 UTC, pombredanne commented
This is looking great!
Can I interest you in adding a small test too?
You could use the section of the file attached by @camillem in https://github.com/nexB/scancode-toolkit/issues/3615 as a test file in this directory https://github.com/nexB/scancode-toolkit/tree/develop/tests/licensedcode/data/datadriven/lic4 with a companion YAML expected results?

2024-02-12 15:54 UTC, AyanSinhaMahapatra commented
@dotarjun 

> Error: Invalid value for '<OUTPUT FORMAT OPTION(s)> <input>...': Path 'custom-content.html.txt' does not exist.

That's because you don't have the file there.
You have to download the custom_content.html.txt mentioned here: https://github.com/nexB/scancode-toolkit/issues/3615#issue-2021184594: https://github.com/nexB/scancode-toolkit/files/13529627/custom-content.html.txt

> scancode ... custom-content.html.txt.json --json-pp custom-content.html.txt.json

By doing this you're scanning the result file and outputting the result there again, why would you want to do that?
Basically we want to reindex the licenses with your change here in the PR, then scan the test file again to see that there are no more similar bugs present for the same case (by scanning with the commands above, you will find another similar bug, and you have to add another required phrase to another rule to fix this). Or as @pombredanne mentioned above you can add a test and make sure the detections are correct, and there you'll se the issue.

And then:
* Go to the branch you have for this PR
* Make sure you do a reindex with ``scancode-reindex-licenses`` so your change in rule is reflected in the index
* Now scan the linked above file

2024-02-12 16:12 UTC, dotarjun commented
Thank you for the guidance. 

I totally missed it as I have my exams going on.

I'll do it tomorrow after my exam. Apologies for taking such a long time.

2024-02-19 01:23 UTC, dotarjun commented
```
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "32.0.8",
      "options": {
        "input": [
          "custom-content.html.txt"
        ],
        "--json-pp": "custom-content.html.txt.json",
        "--license": true,
        "--license-diagnostics": true,
        "--license-references": true,
        "--license-text": true,
        "--license-text-diagnostics": true,
        "--todo": true
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2024-02-19T011934.354644",
      "end_timestamp": "2024-02-19T011938.104192",
      "output_format_version": "3.1.0",
      "duration": 3.7495858669281006,
      "message": null,
      "errors": [],
      "warnings": [],
      "extra_data": {
        "system_environment": {
          "operating_system": "linux",
          "cpu_architecture": "64",
          "platform": "Linux-6.7.1-arch1-1-x86_64-with-glibc2.38",
          "platform_version": "#1 SMP PREEMPT_DYNAMIC Sun, 21 Jan 2024 22:14:10 +0000",
          "python_version": "3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]"
        },
        "spdx_license_list_version": "3.22",
        "files_count": 1
      }
    }
  ],
  "license_detections": [
    {
      "identifier": "cc_by_sa_4_0_and_cc_by_sa_3_0-0626dcd2-0fd9-95cd-1c24-dbf7a0bf1b29",
      "license_expression": "cc-by-sa-4.0 AND cc-by-sa-3.0",
      "license_expression_spdx": "CC-BY-SA-4.0 AND CC-BY-SA-3.0",
      "detection_count": 1,
      "detection_log": [],
      "reference_matches": [
        {
          "license_expression": "cc-by-sa-4.0",
          "license_expression_spdx": "CC-BY-SA-4.0",
          "from_file": "custom-content.html.txt",
          "start_line": 76,
          "end_line": 76,
          "matcher": "3-seq",
          "score": 50.0,
          "matched_length": 11,
          "match_coverage": 50.0,
          "rule_relevance": 100,
          "rule_identifier": "cc-by-sa-4.0_44.RULE",
          "rule_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/cc-by-sa-4.0_44.RULE",
          "matched_text": "and are licensed under <a href=\"http://creativecommons.org/licenses/by-sa/3.0/deed.en\" title=\"Creative Commons Attribution-ShareAlike 3.0\">CC BY-SA 3.0</a> by the copyright holder.</p>",
          "matched_text_diagnostics": "licensed under <a href=\"[http]://creativecommons.org/licenses/by-sa/[3].[0]/[deed].[en]\" [title]=\"Creative Commons Attribution-ShareAlike"
        },
        {
          "license_expression": "cc-by-sa-3.0",
          "license_expression_spdx": "CC-BY-SA-3.0",
          "from_file": "custom-content.html.txt",
          "start_line": 76,
          "end_line": 76,
          "matcher": "2-aho",
          "score": 100.0,
          "matched_length": 6,
          "match_coverage": 100.0,
          "rule_relevance": 100,
          "rule_identifier": "cc-by-sa-3.0_57.RULE",
          "rule_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/cc-by-sa-3.0_57.RULE",
          "matched_text": "and are licensed under <a href=\"http://creativecommons.org/licenses/by-sa/3.0/deed.en\" title=\"Creative Commons Attribution-ShareAlike 3.0\">CC BY-SA 3.0</a> by the copyright holder.</p>",
          "matched_text_diagnostics": "Creative Commons Attribution-ShareAlike 3.0\">"
        },
        {
          "license_expression": "cc-by-sa-3.0",
          "license_expression_spdx": "CC-BY-SA-3.0",
          "from_file": "custom-content.html.txt",
          "start_line": 76,
          "end_line": 76,
          "matcher": "2-aho",
          "score": 50.0,
          "matched_length": 5,
          "match_coverage": 100.0,
          "rule_relevance": 50,
          "rule_identifier": "spdx_license_id_cc-by-sa-3.0_for_cc-by-sa-3.0.RULE",
          "rule_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/spdx_license_id_cc-by-sa-3.0_for_cc-by-sa-3.0.RULE",
          "matched_text": "and are licensed under <a href=\"http://creativecommons.org/licenses/by-sa/3.0/deed.en\" title=\"Creative Commons Attribution-ShareAlike 3.0\">CC BY-SA 3.0</a> by the copyright holder.</p>",
          "matched_text_diagnostics": "CC BY-SA 3.0</"
        }
      ]
    }
  ],
  "todo": [
    {
      "detection_id": "cc_by_sa_4_0_and_cc_by_sa_3_0-0626dcd2-0fd9-95cd-1c24-dbf7a0bf1b29",
      "review_comments": {
        "imperfect-match-coverage": "The license detection likely is not conclusive as there was license matches with low score or coverage, and so this needs review. scancode would likely benifit from a license rule addition from this case, so please report this to scancode-toolkit github issues."
      },
      "detection": {
        "license_expression": "cc-by-sa-4.0 AND cc-by-sa-3.0",
        "license_expression_spdx": "CC-BY-SA-4.0 AND CC-BY-SA-3.0",
        "matches": [
          {
            "license_expression": "cc-by-sa-4.0",
            "license_expression_spdx": "CC-BY-SA-4.0",
            "from_file": "custom-content.html.txt",
            "start_line": 76,
            "end_line": 76,
            "is_license_notice": true,
            "matcher": "3-seq",
            "score": 50.0,
            "matched_length": 11,
            "rule_length": 22,
            "match_coverage": 50.0,
            "rule_relevance": 100,
            "rule_identifier": "cc-by-sa-4.0_44.RULE",
            "rule_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/cc-by-sa-4.0_44.RULE",
            "rule_notes": null,
            "referenced_filenames": [],
            "matched_text": "and are licensed under <a href=\"http://creativecommons.org/licenses/by-sa/3.0/deed.en\" title=\"Creative Commons Attribution-ShareAlike 3.0\">CC BY-SA 3.0</a> by the copyright holder.</p>",
            "rule_text": "This work is licensed under a <a rel=\"license\" href=\"https://creativecommons.org/licenses/by-sa/4.0/\">\nCreative Commons Attribution-ShareAlike 4.0 International License</a>."
          },
          {
            "license_expression": "cc-by-sa-3.0",
            "license_expression_spdx": "CC-BY-SA-3.0",
            "from_file": "custom-content.html.txt",
            "start_line": 76,
            "end_line": 76,
            "is_license_reference": true,
            "matcher": "2-aho",
            "score": 100.0,
            "matched_length": 6,
            "rule_length": 6,
            "match_coverage": 100.0,
            "rule_relevance": 100,
            "rule_identifier": "cc-by-sa-3.0_57.RULE",
            "rule_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/cc-by-sa-3.0_57.RULE",
            "rule_notes": null,
            "referenced_filenames": [],
            "matched_text": "and are licensed under <a href=\"http://creativecommons.org/licenses/by-sa/3.0/deed.en\" title=\"Creative Commons Attribution-ShareAlike 3.0\">CC BY-SA 3.0</a> by the copyright holder.</p>",
            "rule_text": "Creative Commons Attribution-ShareAlike 3.0"
          },
          {
            "license_expression": "cc-by-sa-3.0",
            "license_expression_spdx": "CC-BY-SA-3.0",
            "from_file": "custom-content.html.txt",
            "start_line": 76,
            "end_line": 76,
            "is_license_reference": true,
            "is_continuous": true,
            "matcher": "2-aho",
            "score": 50.0,
            "matched_length": 5,
            "rule_length": 5,
            "match_coverage": 100.0,
            "rule_relevance": 50,
            "rule_identifier": "spdx_ [...]

2024-02-19 09:17 UTC, AyanSinhaMahapatra commented
> I think cc-by-sa-4.0 should not be detected. Am I on the right track?

Yes! Now we have to update `cc-by-sa-4.0_44.RULE` too similarly in the PR.

2024-02-20 05:25 UTC, dotarjun commented
I've been trying to figure out how to do that but I can't understand why that is happening. 

``custom-content.html.txt.json``
```
"matched_text_diagnostics": "licensed under <a href=\"[http]://creativecommons.org/licenses/by-sa/[3].[0]/[deed].[en]\" [title]=\"Creative Commons Attribution-ShareAlike"
```

This makes no sense as in ``cc-by-sa-4.0_44.RULE``
There is no such matching text 
```
---
license_expression: cc-by-sa-4.0
is_license_notice: yes
relevance: 100
ignorable_urls:
    - https://creativecommons.org/licenses/by-sa/4.0/
---

This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">
Creative Commons Attribution-ShareAlike 4.0 International License</a>.
```

2024-02-25 09:40 UTC, pombredanne commented
You should add a test under tests/ IMHO

2024-09-02 13:31 UTC, pombredanne commented
@AyanSinhaMahapatra do you want to wait for a test, or merge this as-is?

2025-04-13 15:08 UTC, pombredanne commented
I am merging, but there are not much changes in the PR at all since there have been many updates in the meantime!

2025-04-13 15:08 UTC, merged