Support SPDX License List 3.23
nexB/scancode-toolkit pull request #3653
Opened 2024-02-14 15:53 UTC by AyanSinhaMahapatra

Reference: https://github.com/nexB/scancode-licensedb/issues/49

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁
* [ ] Updated documentation pages (if applicable)
* [ ] Updated CHANGELOG.rst (if applicable)

2024-02-19 10:45 UTC, pombredanne approved these changes
LGTM! Thanks

2024-02-19 10:50 UTC, pombredanne commented on src/licensedcode/data/rules/fsfap-no-warranty-disclaimer_1.RULE
> +Copyright (C) 2008 Micah J. Cowan
Please do not add a rule with a copyright here. It adds nothing new... copyright will be detected separately ... here this is not a copyright for the license but the code.

2024-02-19 10:51 UTC, pombredanne commented on src/licensedcode/data/rules/gtkbook_1.RULE
> +Copyright 2005 Syd Logan, All Rights Reserved
Same as above... no copyright please

2024-02-19 11:20 UTC, pombredanne approved these changes
Here are a few nits on copyrights... and good to merge otherwise!
Thanks

2024-02-19 11:20 UTC, pombredanne commented on src/licensedcode/data/rules/dec-3-clause_1.RULE
> +Copyright 1997 Digital Equipment Corporation.
No copyrights please

2024-02-19 11:20 UTC, pombredanne commented on src/licensedcode/data/rules/caldera-no-preamble_1.RULE
> +Copyright(C) Caldera International Inc.  2001-2002.  All rights reserved.
No copyright here too

2024-02-19 11:20 UTC, pombredanne commented on src/licensedcode/data/rules/other-permissive_242.RULE
> +is_deprecated: yes
Add also https://github.com/nexB/scancode-toolkit/blob/5a39c2165282731d86fcc7f99cd0677b91a6e389/src/licensedcode/data/rules/other-permissive_241.RULE and https://github.com/nexB/scancode-toolkit/blob/5a39c2165282731d86fcc7f99cd0677b91a6e389/src/licensedcode/data/rules/other-permissive_243.RULE to point to the new mailprio license

2024-02-19 11:20 UTC, pombredanne commented on src/licensedcode/data/rules/pnmstitch_1.RULE
> +Copyright (c) 2002 Mark Salyzyn
No copyright there

2024-02-19 11:20 UTC, pombredanne commented on src/licensedcode/data/rules/softsurfer_2.RULE
> +Copyright 2001, softSurfer (www.softsurfer.com)
No copyright

2024-02-19 11:20 UTC, pombredanne commented on src/licensedcode/data/rules/sun-ppp_1.RULE
> +Copyright (c) 2001 by Sun Microsystems, Inc.
No copyright

2024-02-19 11:20 UTC, pombredanne commented on src/licensedcode/data/rules/umich-merit_1.RULE
> +[C] The Regents of the University of Michigan and Merit Network, Inc. 1992,
See https://github.com/nexB/scancode-toolkit/issues/3659 for reference ./.. so we can keep this copyright for now.

2024-02-19 11:20 UTC, pombredanne commented on src/licensedcode/data/rules/xkeyboard-config-zinoviev_1.RULE
> +Copyright (C) 1999, 2000 by Anton Zinoviev <anton@lml.bas.bg>
No copyright

2024-02-20 14:11 UTC, pombredanne requested changes
Please our texts as-is and add add new rules with the SPDX texts rather than modifying our texts.

2024-02-20 14:11 UTC, pombredanne commented on src/licensedcode/data/licenses/drl-1.1.LICENSE
> +Permission is hereby granted, free of charge, to any person obtaining a copy of this rule set and associated documentation files (the "Rules"), to deal in the Rules without restriction, including wit
Why did you replace our text which is better and properly formatted?
You should IMHO keep our text and add the SPDX text as a detection rule instead.

2024-02-20 14:11 UTC, pombredanne commented on src/licensedcode/data/licenses/hdparm.LICENSE
> +BSD-Style Open Source License:
Please keep our original text and add the SPDX text as a detection rule

2024-02-20 14:11 UTC, pombredanne commented on src/licensedcode/data/licenses/paul-mackerras.LICENSE
> +    <paulus@ozlabs.org>".
Please add our original text with samba.org as a rule too

2024-02-20 14:11 UTC, pombredanne commented on src/licensedcode/data/licenses/softsurfer.LICENSE
> +This code may be freely used and modified for any purpose
Please keep our text as-is and add a rule for the SPDX license text

2024-02-20 14:11 UTC, pombredanne commented on src/licensedcode/data/licenses/tgppl-1.0.LICENSE
> -This Transitive Grace Period Public Licence (the "License") applies to
Please our text as-is and add add a new rule with the SPDX text

2024-02-20 16:04 UTC, AyanSinhaMahapatra commented
@pombredanne thanks for the comments, updated them to preserve the original texts.

2024-02-20 18:58 UTC, DennisClark approved these changes
@AyanSinhaMahapatra   I tried really hard to find problems, but did not succeed!  This looks ready to go, thanks.

2024-02-20 19:05 UTC, AyanSinhaMahapatra commented
Thanks @DennisClark @pombredanne , merging!

2024-02-20 19:06 UTC, merged