Update MSFT related URL rules
nexB/scancode-toolkit pull request #3717
Opened 2024-04-01 19:42 UTC by swastkk

Fixes https://github.com/nexB/scancode-toolkit/issues/3702

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [ ] Commits are in uniquely-named feature branch and has no merge conflicts 📁
* [ ] Updated documentation pages (if applicable)
* [ ] Updated CHANGELOG.rst (if applicable)

2024-06-10 15:59 UTC, AyanSinhaMahapatra requested changes
This is not what we want to do, see comments.

2024-06-10 15:59 UTC, AyanSinhaMahapatra commented on src/licensedcode/data/rules/unknown-license-reference_158.RULE
> +https://dotnet.microsoft.com/en-us/dotnet_library_license.htm
You've misunderstood entirely what we want to do here.

We don't want to change the rule text, we want to change the license_expression for this rule to `ms-net-library-2019-06` as this is a license we now have in licenseDB and so this is not an unknown license reference.

Note that we cannot just change a license-expression by replacing, we have to deprecate this rule and create a new rule, see the comment in https://github.com/nexB/scancode-toolkit/pull/3744#discussion_r1601669862 for example. As this is reference data and we want to preserve these rule names and links to these.

2024-10-04 09:14 UTC, pombredanne commented
ping

2025-04-10 07:53 UTC, pombredanne commented
@swastkk I am closing this for now, as we need a new rule, not an updated of the old one.

2025-04-10 10:05 UTC, closed without merging