Add new rule to fix #3738
nexB/scancode-toolkit pull request #3750
Opened 2024-04-26 08:41 UTC by vasily-pozdnyakov

Fixes #3738

### Tasks

* [x ] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [ x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [ ] Commits are in uniquely-named feature branch and has no merge conflicts 📁
* [ ] Updated documentation pages (if applicable)
* [ ] Updated CHANGELOG.rst (if applicable)

2024-04-26 08:47 UTC, vasily-pozdnyakov commented
Hi, I am new to new rules creation and have a couple of questions:
1. What does scancode-reindex-licenses do? It does not introduce any visible changes...
2. Why most of the rules are weak (without "{{}}")? If I understand correctly, it might bring a lot of false positives (let's say, there is a matching license notice for MIT, but with a different license name (Apache) - the scancode might detect it incorrectly), is it like that?

2024-04-26 12:11 UTC, AyanSinhaMahapatra commented
@vasily-pozdnyakov welcome and thanks for the PR!

> What does scancode-reindex-licenses do? It does not introduce any visible changes (validation is clear, what about reindex?).

When you get SCTK from a git checkout and install scancode to run locally (or get scancode from github releases or pip install) you have the license indexes at `scancode-toolkit/src/licensedcode/data/cache/license_index/` which contains the license index (pre-built if you're downloading the release/via pip) that is used for license detection when you run scancode. Now if you are updating/adding new rule/licenses in scancode you want to run `scancode-reindex-licenses` so next time you run a scan locally these rules are in the index and are used in license detection, but this does no changes in the repository of rules.

> Why most of the rules are weak (without "{{}}")? If I understand correctly, it might bring a lot of false positives (let's say, there is a matching license notice for MIT, but with a different license name (Apache) - the scancode might detect it incorrectly), is it like that?


That's mostly correct, this could (and does also) generate a lot of false positives in a lot of cases. See https://github.com/nexB/scancode-toolkit/issues/2878

We are working on resolving this and I have a pending PR at https://github.com/nexB/scancode-toolkit/pull/3254 testing out adding required phrases automatically and massively across all the rules from the following:
1. license names and other license keywords
2. from other instances of these required phrases added in other rules.
This would improve the accuracy significantly for these rules and also make sure when we add a required phrase, same is marked across the same phrases present in all rules. There is just a bit of work remaining on testing this and verifying this works correctly across all the rules. But this addition of required phrases would be continuous, or a massive one-time effort otherwise.

2024-04-26 12:12 UTC, AyanSinhaMahapatra commented on src/licensedcode/data/rules/mit_and_apache-2.0_10.RULE
> +---
```suggestion
referenced_filenames:
   - LICENSE_MIT
   - LICENSE_APACHE
---
```

2024-06-08 09:44 UTC, pombredanne requested changes
Thanks. Just a minor but important nit wrt. to the license expression. The norm for MIT and Pache in the Rust ecosystem is to be a choice and buck2 and this new rules is not an exception.

We could also later add more rules for derived notices such as https://github.com/facebook/buck2?tab=readme-ov-file#license

2024-06-08 09:44 UTC, pombredanne commented on src/licensedcode/data/rules/mit_and_apache-2.0_10.RULE
> +license_expression: mit AND apache-2.0
```suggestion
license_expression: mit OR apache-2.0
```

As weird as it sounds this is choice of license, not a conjunction. This is the license of BUCK afaik at https://github.com/facebook/buck2 ans https://github.com/facebook/buck2/blob/732db19980a934de534193ec2d4e330a1d251575/ci.bzl#L3 and this a choice of licenses.

2024-06-10 15:37 UTC, AyanSinhaMahapatra commented
Thanks++ @vasily-pozdnyakov, merging!

2024-06-10 15:38 UTC, merged