Improve copyrights detection
nexB/scancode-toolkit pull request #3752
Opened 2024-04-26 14:57 UTC by pombredanne

This PR improves copyright detection

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁
* [x] Updated documentation pages (if applicable)
* [x] Updated CHANGELOG.rst (if applicable)

2024-06-10 15:53 UTC, AyanSinhaMahapatra requested changes
@pombredanne we need to fix the test failures here and after regenerating it seems to me like some of these are regressions potentially, we need more review of these failures.

2024-06-22 13:44 UTC, pombredanne commented
@AyanSinhaMahapatra ready for your review, all greeen

2024-06-24 10:02 UTC, AyanSinhaMahapatra approved these changes
LGTM! I have a couple small questions and fixes here.

2024-06-24 10:02 UTC, AyanSinhaMahapatra commented on src/licensedcode/data/rules/mpl-1.1_or_gpl-2.0-plus_10.RULE
> +    - Portions created by the Initial Developer are Copyright (c) 1997-1999 the Initial Developer
Should this leading text be a part of the copyright detection?

2024-06-24 10:02 UTC, AyanSinhaMahapatra commented on tests/textcode/test_markup.py
> +    def test_jsp_demarkup(self, regen=True):
```suggestion
    def test_jsp_demarkup(self, regen=False):
```

2024-06-26 08:07 UTC, pombredanne commented on src/licensedcode/data/rules/mpl-1.1_or_gpl-2.0-plus_10.RULE
> +    - Portions created by the Initial Developer are Copyright (c) 1997-1999 the Initial Developer
that's a new thing in this batch. Otherwise we have ambiguities when Portions needs to be detected sometimes and not some other times

2024-06-26 10:55 UTC, AyanSinhaMahapatra approved these changes
LGTM! Thanks++ @pombredanne  This improves copyright detection a lot!
Merging!

2024-06-26 10:56 UTC, merged