Add support for Swift package manager
nexB/scancode-toolkit pull request #3788
Opened 2024-05-28 16:10 UTC by keshav-space

- Fixes #2657 

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁
* [x] Updated documentation pages (if applicable)
* [ ] Updated CHANGELOG.rst (if applicable)

2024-05-29 12:25 UTC, pombredanne commented on src/packagedcode/swift.py
> +    default_primary_language = "swift"
```suggestion
    default_primary_language = "Swift"
```

2024-05-29 13:07 UTC, pombredanne requested changes
Thanks! here  are a few feedbacks for you consideration

There are likely a few extra things to consider:
- `.package.resolved` files like in https://github.com/stripe/stripe-ios/blob/ec051a63435807b6c2ab7fbd6efd35f1173325b9/.package.resolved#L2 are created when using only XCode.
- there may be some older legacy format that look like this for the version 1 https://github.com/fastlane/fastlane/blob/806c80c39754034c3dfcdade6beb51bb55c7f3b1/Package.resolved#L2
- and also version 3 https://github.com/Brightify/Cuckoo/blob/b1ff0383512f0ab954e673718098c6c68bdf57b1/.package.resolved#L122C1-L122C16 from xcode?


Unrelated this https://github.com/tuist/tuist/tree/25d90e3a3d613caf6a740a03ea4d195a685a0feb/fixtures/app_with_spm_dependencies/Tuist has some interesting things:
- a workspace
- development dependencies (they cannot be tagged as such anywhere in Swift syntax)

2024-05-29 13:07 UTC, pombredanne commented on src/packagedcode/swift.py
> +``swift package dump-package > Package.swift.json``
```suggestion

-  To create a parsable JSON version of the Package.swift manifest, run this: ``swift package dump-package > Package.swift.json``
```

2024-05-29 13:07 UTC, pombredanne commented on src/packagedcode/swift.py
> +``swift package resolve``
```suggestion
-  To create the Package.resolved lock file, run this: ``swift package resolve``
```

2024-05-29 13:07 UTC, pombredanne commented on src/packagedcode/swift.py
> +    description = "json dump of swift manifest"
```suggestion
    description = "JSON dump of Package.swift created with ``swift package dump-package > Package.swift.json``"
```

2024-05-29 13:07 UTC, pombredanne commented on src/packagedcode/swift.py
> +    description = "resolved dependency for swift package"
```suggestion
    description = "Resolved full dependency lockfile for Package.swift created with ``swift package resolve``"
```

2024-05-29 13:07 UTC, pombredanne commented on src/packagedcode/swift.py
> +    path_patterns = ("*/Package.resolved",)
```suggestion
    path_patterns = ("*/Package.resolved", ".package.resolved",)
```

2024-05-29 13:07 UTC, pombredanne commented on src/packagedcode/swift.py
> +                namespace=None,
Are you sure we have no namespace? See https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#swift IMHO we always need one.
Let's use the last segment as the `name` and the rest before as namespace

2024-05-29 13:07 UTC, pombredanne commented on src/packagedcode/swift.py
> +            namespace=None,
Add namespace

2024-05-29 13:07 UTC, pombredanne commented on src/packagedcode/swift.py
> +                        scope="install",
Let's use the exact name used upstream for the scope which is "dependencies".
```suggestion
                        scope="dependencies",
```

2024-05-29 13:07 UTC, pombredanne commented on src/packagedcode/swift.py
> +            name=name,
we need a namespace always.

2024-05-29 13:07 UTC, pombredanne commented on src/packagedcode/swift.py
> +                scope="install",
```suggestion
                scope="dependencies",
```

2024-05-29 13:07 UTC, pombredanne commented on tests/packagedcode/data/swift/packages/mapboxmaps_manifest/Package.swift.json
> +  "platforms" : [
You may want to keep these as extra data.

2024-05-29 16:09 UTC, keshav-space commented on src/packagedcode/swift.py
> +            namespace=None,
@pombredanne  We don't have a namespace for the top-level package in the Package.swift manifest.

2024-05-30 10:02 UTC, pombredanne commented on src/packagedcode/swift.py
> +            namespace=None,
ok, how does this look like when installed?
Is there any trace of where it came from?
https://github.com/mapbox/mapbox-maps-ios/blob/main/Package.swift has some possible base URL. BUT when I see https://github.com/map-ir/mapir-ios-maps-sdk/blob/cfca260d03ab8f0d1889795ec012adae1d3bfbd8/Package.swift#L20 or https://github.com/mapbox/mapbox-navigation-ios/blob/b9c235e665ea2d3b7cd096e9c6128e97c1d4f00c/Package.swift#L27 it is clear that the actual name is one thing and the "package name" is another thing and seem to be resolved only when interpreting a Package.swift for dependencies.

So IMHO we cannot get that actual correct PURL name short of matching or have this used as a dependency. Just create a follow up issue for this so we can address it later.

2024-05-30 12:50 UTC, keshav-space commented on src/packagedcode/swift.py
> +            namespace=None,
> ok, how does this look like when installed?
> Is there any trace of where it came from?

Yes, we can trace the source of an already installed package from the `.build` directory.

Tracking this issue here https://github.com/nexB/scancode-toolkit/issues/3793
> The PURL for a Swift package depends on where the package is hosted, and given that `Package.swift` does not contain the repository URL for the top-level package, it is not possible to infer the correct PURL for the top-level package solely from the `Package.swift` manifest.
> We can use https://swiftpackageindex.com/ to get the correct PURL, but this may not work for all packages since Swift Package Index is not authoritative in nature, i.e. a Swift package may exist, and the author may choose not to add their package to Swift Package Index. https://swiftpackageindex.com/add-a-package

2024-06-03 08:28 UTC, keshav-space commented
Thanks @pombredanne, addressed all your feedback.

2024-06-03 09:58 UTC, pombredanne approved these changes
All good. Please merge.

2024-06-03 10:59 UTC, merged