Add handler for packages.lock.json in nuget
nexB/scancode-toolkit pull request #3825
Opened 2024-06-24 14:31 UTC by TG1999

Reference: https://github.com/nexB/scancode.io/issues/1263

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁
* [x] Updated documentation pages (if applicable)
* [ ] Updated CHANGELOG.rst (if applicable)

2024-06-25 14:30 UTC, AyanSinhaMahapatra requested changes
Thanks++ @TG1999 

See comments for a few questions and changes.

Also, typically we have lockfiles beside another package manifest right?
I was looking for examples of this and is this `.csproj` files for nuget? Are there other manifests which would be nice to parse and store?
Here is an example of a `.csproj` file and `packages.lock.json` together: https://github.com/ncblakely/GiantsTools/tree/main/Giants.Services to add as tests.
Should we not also do some lightweight package assembly here?

2024-06-25 14:30 UTC, AyanSinhaMahapatra commented on src/packagedcode/nuget.py
> +    def is_datafile(cls, location, filetypes=..., _bare_filename=False):
Why do we need a custom `is_datafile()` function here? Can this be something else than `packages.lock.json`?
Also we need tests for this function, similar to the `test_nuspec_is_package_data_file` function for another parser, for different cases of this datafile name.

2024-06-25 14:30 UTC, AyanSinhaMahapatra commented on src/packagedcode/nuget.py
> +    documentation_url = 'https://docs.microsoft.com/en-us/nuget/reference/packages-lock-file'
This redirects to https://learn.microsoft.com/en-us/nuget/reference/packages-lock-file and gives a 404

2024-06-25 14:30 UTC, AyanSinhaMahapatra commented on src/packagedcode/nuget.py
> +        for dep in package_info.get('dependencies', {}):
Can this `package_info.get('dependencies', {})` be refactored into a variable so we can use it below instead of doing `package_info["dependencies"][dep]`

2024-06-25 14:30 UTC, AyanSinhaMahapatra commented on src/packagedcode/nuget.py
> +                dependencies = NugetPackagesLockHandler.get_dependencies(package_info=package_info, scope=target_framework)
We can just make `get_dependencies` a classmethod and do cls.get_dependencies here, as this is not used anywhere alse atm.

2024-06-25 14:30 UTC, AyanSinhaMahapatra commented on src/packagedcode/nuget.py
> +                    raise Exception(f"Unknown package type: {package_type}")
Can we make this a bit ore descriptive with the Class name and location of the error.

2024-06-25 14:30 UTC, AyanSinhaMahapatra commented on src/packagedcode/nuget.py
> +            # TODO: Check if we to put virtual or private for packages without a name and version
These are not required to set, IMHO, according to current practice elsewhere, you can remove this comment.

2024-06-25 14:30 UTC, AyanSinhaMahapatra commented on tests/packagedcode/data/nuget/packages.lock.json.expected
> +              "is_direct": false,
```suggestion
              "is_direct": true,
```

`is_direct: True` is not only for the direct dependencies of the main root package, but also for all direct dependency relationships of transitive dependencies.

2024-06-25 14:30 UTC, AyanSinhaMahapatra commented on src/packagedcode/nuget.py
> +                is_direct=False,
```suggestion
                is_direct=True,
```
`is_direct: True` is not only for the direct dependencies of the main root package, but also for all direct dependency relationships of transitive dependencies.

2024-06-25 17:12 UTC, TG1999 commented
Adressed all review comments, feel free to merge.

2024-06-26 08:42 UTC, AyanSinhaMahapatra approved these changes
LGTM!
Thanks++ @TG1999 merging!

2024-06-26 08:44 UTC, merged