Added support for parsing private classifier
nexB/scancode-toolkit pull request #3989
Opened 2024-11-17 15:24 UTC by VarshaUN

Fixes #3968

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

Signed-off-by: Varsha U N <varshaun58@gmail.com>

2024-11-29 12:02 UTC, AyanSinhaMahapatra requested changes
@VarshaUN Thanks++

Please always run subset of tests where you have made changes locally and look for test failures. And then also look for test failures in the CI and fix any issues present there too.

2024-11-29 12:02 UTC, AyanSinhaMahapatra commented on tests/packagedcode/test_pypi.py
> +        test_file = self.get_test_loc('pypi/pyproject-toml/private/private_package/pyproject.toml')
You've added a test but no test file, so this is failing with an OSError, no file found. Please add the corresponding test and expected files too. See https://scancode-toolkit.readthedocs.io/en/stable/contribute/contrib_dev.html#running-tests on how to regen files selectively.

2024-11-29 12:02 UTC, AyanSinhaMahapatra commented on src/packagedcode/pypi.py
> +        extra_data['is_private'] = is_private
We don't need to store these in `extra_data`, as we have a proper field for this at https://github.com/aboutcode-org/scancode-toolkit/blob/develop/src/packagedcode/models.py#L696 which I added sometime back here: https://github.com/aboutcode-org/scancode-toolkit/commit/f848741989d0d40309fc1220c58b5a9a145c897e See related issues and files for more examples on how it was added.

2024-12-24 01:48 UTC, VarshaUN commented
@AyanSinhaMahapatra  I have added every required files now. Please review it

2024-12-24 12:34 UTC, VarshaUN commented
@AyanSinhaMahapatra I have added the changes you told me. Please review it

2025-01-06 10:10 UTC, closed without merging