Added new license rules for new Elasticsearch notices
nexB/scancode-toolkit pull request #4041
Opened 2024-12-28 18:08 UTC by NucleonGodX

Fixes #3942 

### Tasks

* [x] Reviewed [contribution guidelines](https://github.com/nexB/scancode-toolkit/blob/develop/CONTRIBUTING.rst)
* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] Tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
  Run [tests](https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html#running-tests) locally to check for errors. 
* [x] Commits are in uniquely-named feature branch and has no merge conflicts 📁

Signed-off-by: NucleonGodX [manitsingh018@gmail.com](mailto:manitsingh018@gmail.com)

2025-04-07 10:40 UTC, AyanSinhaMahapatra requested changes
@NucleonGodX Thanks for the PR.
Please see my comments for your consideration.

2025-04-07 10:40 UTC, AyanSinhaMahapatra commented on src/licensedcode/data/rules/elastic-license-v2_or_agpl-3.0_or_mongodb-sspl-1.0_2.RULE
> +license_expression: (elastic-license-v2 OR agpl-3.0 OR mongodb-sspl-1.0) AND apache-2.0 AND elastic-license-v2
```suggestion
license_expression: elastic-license-v2 OR agpl-3.0 OR mongodb-sspl-1.0
```
You also have to change the rule file name accordingly.

2025-04-07 10:40 UTC, AyanSinhaMahapatra commented on src/licensedcode/data/rules/elastic-license-v2_or_agpl-3.0_or_mongodb-sspl-1.0_3.RULE
> +relevance: 100
Add:
```
minimum_coverage: 95
```

2025-04-07 10:40 UTC, AyanSinhaMahapatra commented on src/licensedcode/data/rules/elastic-license-v2_or_agpl-3.0_or_mongodb-sspl-1.0_1.RULE
> + * 2.0", the "{{GNU Affero General Public License v3.0 only}}", and the "{{Server Side
Include the 2.0 in the required phrase: "{{Elastic License 2.0}}"
Also add the required phrase to all the instances of license names over this rules and other rules you've added to this PR.

2025-04-14 11:14 UTC, NucleonGodX commented
Thanks for the review @AyanSinhaMahapatra

2025-04-21 19:50 UTC, pombredanne approved these changes
Looking fine. I will squash merge to get a cleaner history.
Thanks

2025-04-21 19:52 UTC, merged